version: '3'

services:
  db:
    image: postgres
    container_name: db_container_project
    environment:
      POSTGRES_DB: db_project
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    depends_on:
      - db




