version: '3'

services:
  db:
    image: postgres
    container_name: db_container_project
    hostname: db
    environment:
      POSTGRES_DB: db_project
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    image: apolline/db
    volumes : 
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    image: apolline/app
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/db_project
    depends_on:
      - db
    volumes:
      - /home:/home
volumes:
  postgres_data:
      




