name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker-compose build

    - name: Start services
      run: docker-compose up -d

    - name: Run tests
      run: docker-compose exec -T app mvn test

    - name: Push Docker image
      if: success()
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker-compose push

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        aws-session-token: ${{ secrets.AWS_SECRET_TOKEN }}

    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ec2-54-242-73-204.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_AWS_KEY }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -aG docker $USER
          exit

    - name: Pull and run image docker
      uses: appleboy/ssh-action@master
      with:
        host: ec2-54-242-73-204.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_AWS_KEY }}
        port: 22
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          export DOCKER_USERNAME=apolline
          wget https://raw.githubusercontent.com/apollineguerineau/genie_logiciel/main/docker-compose.yml
          docker-compose pull
          # docker-compose up
##
  